### ISSUE TITLE
add 'build custom jquery' rule

### ISSUE THREAD

**Issue by jpsc** [voorhoede/jquery-style-guide#14]
It's possible to remove most of the avoidable rules here defined by removing and documenting them with a [custom build of jQuery](https://github.com/jquery/jquery#custom-build-examples).

**Comment by Ex-iT** [comment]
In the General information PR it's mentioned (https://github.com/voorhoede/jquery-style-guide/pull/6) that you can create a custom build.

Suggestion per rule are given if a module is not need, I think that covers this issue.
