### ISSUE TITLE
[hidden] attribute a best practise?

### ISSUE THREAD

**Issue by reinoute** [voorhoede/jquery-style-guide#20]
I'm reading that we encourage using the hidden attribute instead of show/hide, but I believe that according to the spec it's not correct:

> The hidden attribute must not be used to hide content that could legitimately be shown in another presentation. For example, it is incorrect to use hidden to hide panels in a tabbed dialog, because the tabbed interface is merely a kind of overflow presentation — one could equally well just show all the form controls in one big page with a scrollbar. It is similarly incorrect to use this attribute to hide content just from one presentation — if something is marked hidden, it is hidden from all presentations, including, for instance, screen readers.

https://html.spec.whatwg.org/multipage/interaction.html#the-hidden-attribute

There are many ways to hide/show something, and each has it's own purpose:
1. display:none
2. visibility:hidden (don’t show, but still hold the space)
3. opacity:0
4. width:0;height:0
5. aria-hidden="true"
6. input type="hidden"
7. hidden attribute
8. hidden for screenreader properties (clip, etc)

**Comment by jbmoelker** [comment]
I get your point. I do think the intro to that section sums it up though:

> All HTML elements may have the hidden content attribute set. The hidden attribute is a boolean attribute. When specified on an element, it **indicates that the element is not yet, or is no longer, directly relevant to the page's current state**, 
> -- https://html.spec.whatwg.org/multipage/interaction.html#the-hidden-attribute

jQuery show() / hide() changes display depending on such state. [`[hidden]` does just that for all presentations](https://www.paciellogroup.com/blog/2012/05/html5-accessibility-chops-hidden-and-aria-hidden/) (visually, and in the accessibility tree).

I'm not saying you should use the `[hidden]` technique for tabs, but nor should you use jQuery show() / hide(). Just toggle `[aria-hidden]` on `[role="tabpanel"]` instead.

Should we extend the guideline in this guide to include, in case `[hidden]` is not appropriate, consider toggling `[aria-hidden]` or a class (e.g. `.is-active`)?

**Comment by reinoute** [comment]
Explaining all techniques is probably outside the scope of the style guide (explaining in just a few lines could make it only more confusing). I think we should rather list the different techniques to show/hide content and link to articles explaining those techniques.

**Comment by jpsc** [comment]
Closing.

> Explaining all techniques is probably outside the scope of the style guide (explaining in just a few lines could make it only more confusing).
